---
detector_name: prophet

anomalies: Anomalies_Synthetic_17.csv

create_synthetic_data:
  to_create: False
  filename: Synthetic_17.csv

output:
  csv: True
  plot: True

preprocess_data_params:
  test: False
  test_period:
    hours: 0
    days: 0
    weeks: 2
  fill: ignore
  skiprows: 0

experiment_hyperparameters:
  train_period:
    hours: 3
    days: 0
    weeks: 3
  train_freq:
    hours: 12
    days: 0
    weeks: 0
  forecast_period_hours: 3
  include_train_time: True
  remove_outliers: True
  scale: False

model_hyperparameters:
  esd:
    anomaly_ratio: 0.01
    hybrid: True
    alpha: 0.05

  arima:
    seasonality: 6

  lstm_ae:
    hidden_layer: 128
    dropout: 0.1
    batch_size: 16
    threshold: 99

  prophet:
    interval_width: 0.999
    changepoint_prior_scale: 0.5
    daily_seasonality: 10
    weekly_seasonality: 10
    holidays_country_name:

metadata:
#  - source: csv
#    filename: Sensor U106748.csv
#    attribute_name: internaltemp
#    time_column: Time
#  - source: csv
#    filename: 54863.csv
#    attribute_name: temperature
#    time_column: TSMeasurement
#  - source: csv
#    filename: Sensor U106755.csv
#    attribute_name: internaltemp
#    time_column: Time
  - source: csv
    filename: Synthetic_17.csv
    attribute_name: Value
    time_column: index
#  - source: csv
#    filename: 100330_orig.csv
#    attribute_name: temperature
#    time_column: TSMeasurement