---
detector_name: esd

preprocess_data_params:
  test: False
  test_period:
    hours: 0
    days: 1
    weeks: 0

experiment_hyperparameters:
  train_period:
    hours: 0
    days: 0
    weeks: 4
  forecast_period_hours: 24
  retrain_schedule_hours: 24
  scale: False

model_hyperparameters:
  esd:
    anomaly_ratio: 0.001
    hybrid: True
    alpha: 0.05

  arima:
    seasonality: 6

  lstm_ae:
    hidden_layer: 128
    dropout: 0.1
    batch_size: 16
    threshold: 99

metadata:
#  - filename: Sensor U106748.csv
#    attribute_name: internaltemp
#    time_column: Time
#  - filename: 54863.csv
#    attribute_name: temperature
#    time_column: TSMeasurement
  - filename: Sensor U106755.csv
    attribute_name: internaltemp
    time_column: Time