---
detector_name: lstm_ae

preprocess_data_params:
  test: True
  test_period:
    hours: 0
    days: 1
    weeks: 0

experiment_hyperparameters:
  train_period:
    hours: 0
    days: 1
    weeks: 0
  forecast_period_hours: 1
  retrain_schedule_hours: 1
  scale: True

model_hyperparameters:
  esd:
    anomaly_ratio: 0.001
    hybrid: False
    alpha: 0.05

  arima:
    seasonality: 6

  lstm_ae:
    hidden_layer: 128
    dropout: 0.1
    batch_size: 16
    threshold: 99

metadata:
  - filename: Sensor U106748.csv
    attribute_name: internaltemp
    time_column: Time
#  - filename: 54863.csv
#    attribute_name: temperature
#    time_column: TSMeasurement
#  - filename: Sensor U106755.csv
#    attribute_name: internaltemp
#    time_column: Time
