---
detector_name: arima

create_synthetic_data:
  to_create: True
  filename: Synthetic.csv

output:
  csv: False
  plot: False

preprocess_data_params:
  test: False
  test_period:
    hours: 0
    days: 0
    weeks: 2
  fill: ignore
  skiprows: 6

experiment_hyperparameters:
  train_period:
    hours: 0
    days: 8
    weeks: 0
  train_freq:
    hours: 0
    days: 1
    weeks: 0
  forecast_period_hours: 3
  scale: False

model_hyperparameters:
  esd:
    anomaly_ratio: 0.01
    hybrid: True
    alpha: 0.05

  arima:
    seasonality: 6

  lstm_ae:
    hidden_layer: 128
    dropout: 0.1
    batch_size: 16
    threshold: 99

  prophet:
    interval_width: 0.9

metadata:
#  - source: csv
#    filename: Sensor U106748.csv
#    attribute_name: internaltemp
#    time_column: Time
#  - source: csv
#    filename: 54863.csv
#    attribute_name: temperature
#    time_column: TSMeasurement
#  - source: csv
#    filename: Sensor U106755.csv
#    attribute_name: internaltemp
#    time_column: Time
  - source: csv
    filename: Synthetic.csv
    attribute_name: Value
    time_column: index