---
detector_name: lstm_uncertainty

anomalies:
  filename:
  index:

output:
  csv: True
  plot: True
  features_to_plot:

create_synthetic_data:
  to_create: false
  num_of_series: 5
  period:
    minutes: 0
    hours: 0
    days: 0
    weeks: 4
  freq: 10min
  higher_freq: False
  holiday: False
  weekend: False
  filename: Synthetic_t.csv

preprocess_data_params:
  test: False
  test_period:
    minutes: 0
    hours: 0
    days: 0
    weeks: 2
  fill: bfill #ignore, bfill, ffill, interpolate
  skiprows: 0

experiment_hyperparameters:
  train_period:
    minutes: 0
    hours: 0
    days: 0
    weeks: 3
  train_freq:
    minutes: 0
    hours: 12
    days: 0
    weeks: 0
  forecast_period:
    minutes: 10
    hours: 0
    days: 0
    weeks: 0
  include_train_time: False
  remove_outliers: True
  scale: True


model_hyperparameters:
  esd:
    anomaly_ratio: 0.01
    hybrid: True
    alpha: 0.05

  arima:
    seasonality: 6

  prophet:
    interval_width: 0.999
    changepoint_prior_scale: 0.5
    daily_seasonality: 10
    weekly_seasonality: 10
    holidays_country_name:

  lstm_ae:
    hidden_layer: 64
    dropout: 0.2
    batch_size: 32
    threshold: 99
    val_ratio: 0.2

  lstm_uncertainty:
    hidden_layer: 256
    dropout: 0.1
    batch_size: 32
    val_ratio: 0.1
    lr: 0.00005
    input_timesteps_period:
      minutes: 0
      hours: 6
      days: 0
      weeks: 0

  lstm_ae_uncertainty:
    encoder_dim: 64
    dropout: 0.1
    batch_size: 32
    val_ratio: 0.1
    lr: 0.0005
    input_timesteps_period:
      minutes: 0
      hours: 6
      days: 0
      weeks: 0


metadata:
#  - source: csv
#    filename: Sensor U106748.csv
#    attribute_names:
#      - internaltemp
#      - internalrh
#    time_column: Time
#  - source: csv
#    filename: 54863.csv
#    attribute_names:
#      - temperature
#    time_column: TSMeasurement
#  - source: csv
#    filename: Sensor U106755.csv
#    attribute_names:
#      - internaltemp
#    time_column: Time
#  - source: csv
#    filename: Sensor U100309.csv
#    attribute_names:
#     - internalrh
#     - internaltemp
#    time_column: Time
  - source: csv
    filename: Sensor U100310.csv
    attribute_names:
      - internalrh
      - internaltemp
    time_column: Time
    freq: 10min
#  - source: csv
#    filename: Synthetic_t.csv
#    attribute_names:
#      - all
#    time_column: index
#     freq: 10min