---
detector_name: lstm_uncertainty

anomalies_file_name: Anomalies_Synthetic_t.csv

create_synthetic_data:
  to_create: True
  num_of_series: 1
  higher_freq: False
  holiday: False
  weekend: False
  filename: Synthetic_t.csv

output:
  csv: True
  plot: True

preprocess_data_params:
  test: False
  test_period:
    hours: 0
    days: 0
    weeks: 2
  fill: ignore
  skiprows: 0

experiment_hyperparameters:
  train_period:
    hours: 0.5
    days: 0
    weeks: 2
  train_freq:
    hours: 3
    days: 0
    weeks: 0
  forecast_period_hours: 0.5
  include_train_time: True
  remove_outliers: False
  scale: True


model_hyperparameters:
  esd:
    anomaly_ratio: 0.01
    hybrid: True
    alpha: 0.05

  arima:
    seasonality: 6

  lstm_ae:
    hidden_layer: 64
    dropout: 0.2
    batch_size: 32
    threshold: 99
    val_ratio: 0.2

  lstm_uncertainty:
    hidden_layer: 64
    dropout: 0.1
    batch_size: 32
    val_ratio: 0.1
    lr: 0.00005

  prophet:
    interval_width: 0.999
    changepoint_prior_scale: 0.5
    daily_seasonality: 10
    weekly_seasonality: 10
    holidays_country_name:

metadata:
#  - source: csv
#    filename: Sensor U106748.csv
#    attribute_names:
#      - internaltemp
#    time_column: Time
#  - source: csv
#    filename: 54863.csv
#    attribute_names:
#      - temperature
#    time_column: TSMeasurement
#  - source: csv
#    filename: Sensor U106755.csv
#    attribute_names:
#      - internaltemp
#    time_column: Time
#  - source: csv
#    filename: Sensor U116378.csv
#    attribute_names:
#      - internalrh
#      - internaltemp
#    time_column: Time
  - source: csv
    filename: Synthetic_t.csv
    attribute_names:
      - all
    time_column: index